### PR TITLE
Add ximmio waste collector

### PR DESCRIPTION
**Pull request by basschipper**

### CODE REVIEW

**Comment by pippyn** [comment]
Nice work Bas,

I know the code is really hacky at places. ;)  Thanks for cleaning up a bit. 
I'll refactor the code soon.

Maybe we should add a warning for current  Meerlanden users around line 250. (Just like the warning for Cure users). And change  `waste_collector` to `Ximmio`?

Why didn't you declare the `companyCode` in the init of `XimmioCollector`?

**Comment by basschipper** [comment]
When I got some more spare time I'll check if we can get rid of the `COLLECTOR_WASTE_ID`.

I added the warning you suggested.

I moved the companyCode to the init, not sure why I did this in the first place. Also not sure what the purpose of this attribute is. But as an MVP this is ok I guess.

**Comment by pippyn** [comment]
> When I got some more spare time I'll check if we can get rid of the COLLECTOR_WASTE_ID.

That would be nice!

> Also not sure what the purpose of this attribute is.

Isn't that the Meerlanden identifier? 

I merged the PR and will update the docs and bumb version. After that I will draft a new release.
Thanks again!

**Comment by basschipper** [comment]
Yeah, I think you're right. We might need to change this to a parameter if more municipalities start using Ximmio. But for now it's ok.

Was just having a look at your other repositories, but with the current code structure we're able to integrate those afval projects aswell, what do you think?

**Comment by pippyn** [comment]
> Yeah, I think you're right. We might need to change this to a parameter if more municipalities start using Ximmio. But for now it's ok.

Agreed. 

Yes indeed, we can migrate the Belgium waste sensor and the Groningen to this sensor (Both are not up to date feature wise anyway). It has been on my agenda for a while now, but I'm a bit short on time lately.

**Pull request merged**
