### PR TITLE
ADD Support for DeAfvalApp

### PR DESCRIPTION
**Pull request by coolriku**
I Wrote a draft variant to support the "DeAfvalApp" Collector.
I'm not an Python expert, so there may be some bugs in it.

Please review the changes and implement this new Collector.

### CODE REVIEW

**Comment by pippyn** [comment]
I would love to add support for DeAfvalApp. But we are in the middle of refactoring the code right now. So we will have to wait for now with the PR as a lot is going to change. I'll come back to you as soon as possible. Thanks for your contribution!

**Comment by pippyn** [comment]
This PR is not going to work anymore because of the refactoring. But I took a look at your code and adapted it to the new format. Can you test the code for me?
https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/deafvalapp/custom_components/afvalbeheer/sensor.py

**Comment by coolriku** [comment]
I've tested the new code, and it works as expected, thanks for finishing the code!

**Comment by pippyn** [comment]
Released v4.1.0 with support for DeAfvalApp

**Pull request closed without merging**
