### PR TITLE
WIP: Refactoring

### PR DESCRIPTION
**Pull request by basschipper**
Hi Pippijn,

This is still a WIP, but let me ask your opinion first!

I had some time to do some more cleanup. The idea behind the code structure is that every collector produces it's own unified WasteCollection objects (holding the date and type, not sure if I like the icon_data as it's only supported by the OpzetCollector).
All WasteCollection objects are then stored in the WasteCollectionRepository which is accessible by the sensor. The sensors can ask the repository for thing like give me the next paper collection (`get_next_by_type()`) or what is collected on date x (`get_by_date()`).

Things to-do:
* Find a nice way to handle the translations
* As every collector now holds it's own type mapping I need to test if I didn't missed some
* Hook up with your latest changes (eg. currently missing ophaalkalender.be)
* Still support the OpzetCollector icons?
* ...

What do you think?

### CODE REVIEW

**Comment by pippyn** [comment]
Hi Bas,

First of all; Nice work!!

Your code is so much cleaner! I understand icon_data is not preferred, but I know for a fact it's used a lot by the users and we can't remove it at this point. (I tried, but there was a lot of backlash)

About the TODO's:
- translations; I would be happy to, but I spend a lot off time improving this and I couldn't come up with a better way. 
- I can do the testing for the mapping (when we are ready to merge).
- Not only ophaalkalender is missing, but also the latest addition; an option for the state of the sensor to be a date object (instead of a string). This way the component doesn't do the date formatting, but lovelace does. An example is the [entities card](https://www.home-assistant.io/lovelace/entities/#format).
- I will test the support  for the OpzetCollector icons, but as far as I can see they should still work.

Overall:
- Thank you for your work so far. I know it wasn't easy!
- I approve the renaming of some variables, makes it more clear.
- Thank god we can ditch the COLLECTOR_WASTE_ID
- Do you have time to implement ophaalkalender and the state=date_object? Then I need to do some testing and we can release version 4.0.0

**Comment by basschipper** [comment]
Did a quick rebase on master. So the ophaalkalender and date_object are also in there. I'll think of a better solution to the translations later. Let's first test everything and merge. So that other PR's don't have to wait.

**Comment by pippyn** [comment]
Well done! I will do some test and will let you know tomorrow!

**Comment by pippyn** [comment]
Every wastecollector config I tested failed. Even the ximmio collector config. There are no errors, but all the sensors stay unknown. I did some troubleshooting and noted that line 176 always returns None:
```
        return list(filter(lambda x: x.date.date() >= today.date() and x.waste_type == waste_type, self.get_sorted()))
```
Can you test with test config:
```
  - platform: afvalbeheer
    wastecollector: meerlanden
    resources:                       
      - restafval
    postcode: 2131AN      
    streetnumber: 13
```
[It should report 30april ](https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/calendar.html?1000042772&IJpolderstraat---13%20%20%20---2131AN---Hoofddorp---Haarlemmermeer)

**Comment by basschipper** [comment]
Not sure how that throttle thing works. I switched to async updating, which is in conjunction with API's better anyway.

**Comment by pippyn** [comment]
Async works way better I see. 
Changed an small error in the Ophaalkalender class.
But Ophaalkalender and Opzetcollector sensors are still unknown. And I can't see why..
Can you take a look?
```
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources:
      - Restafval
    postcode: 8650
    streetnumber: 38
    streetname: Beukhoutstraat
  - platform: afvalbeheer
    wastecollector: suez
    resources:                       
      - restafval
    postcode: '6846HS'   
    streetnumber: 1
```

**Comment by basschipper** [comment]
The mapping for the ophaalkalender was incorrect. The example config you sent me has only data for af few types, so I can't fully complete the mapping. Maybe you can help.

The opzet collector is giving me quite some pain. Previously the `menu_title` or `title` from the API was used to do the mapping aka renaming. But as every Opzet user/municipal is using a different name for the same waste type I thought they were all using the same icons, so I switched to icons. But now it seems like the can also have there own icons... :(
So, now what? Back to `title` or `menu_title` and expand the mapping?

**Comment by pippyn** [comment]
Ahh thats what I missed. I will test the other resources.

Yes we can't rely on the icons. Not all wastecollectors use the icons. And the problem is some collectors use `Menu_title` for the fraction name and some use the `title`. That's why there is the check in the current sensor.

**Comment by basschipper** [comment]
Are you sure this was/is working correctly? For instance in the Suez example I see the following `menu_title` and `title` types: "Groente-, fruit en tuinafval", "Papier en karton" and "Plastic, blik & drinkpakken". But, none of them are in the `RENAME_TITLES`? Or am I missing something here?

**Comment by pippyn** [comment]
They are in rename_titles. it's not an exact match.
Example: if the title contains the word "groente" the fraction is "GFT".

That is also what i'm noticing now. With the current sensor it is possible to add a resource that is not mapped, as long as the naming is exactly the same. For example: if the waste collector collects batteries and the fraction is called "Batterijen" by the waste collector. You could add a line under resources named "Batterijen".
This way we don't need to map all the fractions.

**Comment by basschipper** [comment]
It took me quite some time to figure out what you meant by fraction testing, lol. But I restored this way of mapping for the opzetcollector. The suez address you mentioned does not have restafval collection, but gft is working for my.
The API of Ximmio is currently down or slow, so I couldn't complete all test, will try again in the afternoon.

**Comment by pippyn** [comment]
I'm so sorry. That was an old Suez config I had for testing.

Why did you add another `map_waste_type()`? if we just replace the other one all should still work.

OpzetCollector is working now. But can you clear up something for me? If a fraction is not in `WASTE_TYPE_MAPPING{}` the sensor will not work, correct?

**Comment by basschipper** [comment]
Every collector can do exact mapping except for the opzet collector. Because of this, I thought let's have the opzet collector override the default way of mapping. What's your opinion about this?

Indeed, if a fraction is not in the mapping there is no data available to the sensor. Same goes for the current code, although it might not look like that. In current code the fraction mapping creates a relation between the data dict in the collector and the COLLECTOR_WASTE_ID dict. If the fraction renaming failed, then you just got two separate dicts which are useless to the sensor. And this condition will be false: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/master/custom_components/afvalbeheer/sensor.py#L626

We could test this by "destroying" the current mapping, like this:
```
RENAME_TITLES = {
    'xxxduobak': 'duobak',
    'xxxgft gratis': 'gft gratis',
    'xxxgroente': 'gft',
...
```

**Comment by pippyn** [comment]
No that's not true. The current sensor uses the RENAME_TITLES as a renaming dictionary. For titles that are complicated (or sometimes the waste collector adds their name to every fraction). 

If we replace the map_waste_type() with this code:
```
     def map_waste_type(self, name):
        for from_type, to_type in self.WASTE_TYPE_MAPPING.items():
            if from_type in name.lower():
                return to_type
        return name 
```
Then all fractions are available even though they are not mapped.  This should not affect the working of Ximmio or any other integration

**Comment by basschipper** [comment]
You sure? I just did a test with:
```
RENAME_TITLES = {
    'xxxgroente': 'gft',
    'xxxtuinafval': 'gft',
...
```
The sensor is giving `None` now.

Nevertheless, I'm ok with changes the default map function.

**Comment by pippyn** [comment]
Yes im sure, because the names that are in the rename_title do need a renaming for them to work. I will do some last testing when ximmio is back up and running. Thanks for your work bas!

**Comment by pippyn** [comment]
All checks are done (except Ximmio, still down for me). Once Ximmio is back online and tested I'll merge the PR.
Alright by you?

**Comment by basschipper** [comment]
Sounds good. Thanks for fixing the mappings.

The Ximmio api is responding again, but with errors. Hopefully someone will notice tomorrow....

I'll try to keep an eye on the issue page.

**Comment by pippyn** [comment]
Ximmio is back online and working fine! Merging PR

**Pull request merged**
