### PR TITLE
Add sortibak for Omrin

### PR DESCRIPTION
**Pull request by Romkabouter**

### CODE REVIEW

**Comment by pippyn** [comment]
What is the point of this pr? Without these lines stortbak works fine. This doesn't change a thing?

**Comment by Romkabouter** [comment]
Unfortunately, sortibak does not work on my zipcode (8435TH,12)
I saw sortibak commented out, when I debugged the code the Omschrijving for Sortibak was "sortibak", which was not mapped via map_waste_type and therefore skipped.

**Comment by pippyn** [comment]
I know it's commented out, because there is no need for a waste type mapping of `sortibak`. I just tried your address with the current verison of the sensor and it works fine:
```
- platform: afvalbeheer
  wastecollector: Omrin
  resources:
  - sortibak
  postcode: 8435TH
  streetnumber: 12
```
image

**Comment by pippyn** [comment]
I do notice `GFT` is not working for me for that address. Because the fraction in the API is named `GFT verzamel` and not `GFT`. I'll add the fix to your PR and will merge. I stand by the fact that it is not needed to add Sortibak to the mapping, but it doesn't hurt either.

**Comment by pippyn** [comment]
Added in v4.3.2

**Comment by Romkabouter** [comment]
Hmm, I have double checked my version and I am using the latest version. Thanks for the merge

**Pull request merged**
