### PR TITLE
Add support for letter in address

### PR DESCRIPTION
**Pull request by liudger**

### CODE REVIEW

**Comment by liudger** [comment]
I am not a coder so I hope this solution is ok. Couldn't test it though. 
Its easier to test if you make a lib I suppose

**Comment by pippyn** [comment]
Well I see where you're going with this. This is not the most elegant solution though, but the start is there. Thanks for the clarification :)
I'll write the lines needed, but i'll need an address to test with... Can you [DM me on the HA forum](https://community.home-assistant.io/u/Pippyn/) maybe?

PS I really don't see how testing would be easier if there was a lib tbh. Now you just replace/edit the code in sensor.py and restart HA.
PPS There will be a lib made when this project is mature.

**Comment by liudger** [comment]
The other way is that we add the option the user could input a letter(toevoeging) for the street adres

**Comment by pippyn** [comment]
I know, there already is. :)
I'm testing the code now.

**Comment by pippyn** [comment]
Try v4.7.3 with a config like this (add the options you want):
```
  - platform: afvalbeheer
    wastecollector: rmn
    resources:
      - restafval
      - gft
      - papier
      - pmd
    postcode: 1111AA
    streetnumber: 123
    suffix: A
```

**Pull request closed without merging**
