### PR TITLE
Added Peel en Maas

### PR DESCRIPTION
**Pull request by tuimz**
Seems like my municipality uses the same system.

Feel free to increase the version number yourself ;)

### CODE REVIEW

**Comment by pippyn** [comment]
do you have a postcode and streetnumber for me to test with?

**Comment by tuimz** [comment]
5988KA 51 ( a random address nearby me )

**Comment by tuimz** [comment]
Any luck? If there is something that needs changing let me know. Also
tomorrow is garbage day for us ;)

**Comment by tuimz** [comment]
Hate to bug you again but any reason why this is not being merged and released?

**Comment by pippyn** [comment]
I'm sorry. I thought I already did. Will merge it now.

**Pull request merged**
